name: eeashukla
recipe: acquia
config:
  webroot: 'docroot'
  acli_version: latest
  ah_application_uuid: 42017c7c-428e-4979-b7ae-0ec2568ed757
  ah_site_group: eeashukla
  xdebug: true
  php: '7.4'

services:
  appserver:
    xdebug: true
    app_mount: delegated
    ssl: true
    type: php:7.4
    composer_version: 1-latest
    build_as_root:
      - apt-get update -y
      - apt-get install netcat -y
      - apt-get install vim -y
    build:
      - bash /app/.lando/scripts/install-npm.sh
    run_as_root:
      # By default disable XDEBUG, we need it enabled to ensure all configurations are loaded.
      # Post this to enable disable lando xdebug-on and lando xdebug-off can be used.
      - rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && service apache2 reload
      - chown www-data:www-data /run/host-services/ssh-auth.sock
      - chmod g+w /run/host-services/ssh-auth.sock
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=eeashukla"
        SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
      # Pass SSH keys.
      volumes:
        - type: bind
          # Linux user: add 'export LANDO_SSH_AUTH_SOCK="${SSH_AUTH_SOCK}"' at the end of your ~/.bashrc:
          # Mac user: MacOS specific path is here as the variable default value, nothing to do.
          source: "${LANDO_SSH_AUTH_SOCK:-/run/host-services/ssh-auth.sock}"
          target: /run/host-services/ssh-auth.sock

proxy:
  #  edge:
  #    - "*.varnish.eeashukla.lndo.site"
  appserver:
    - "eeashukla.lndo.site"

tooling:
  blt:
    service: appserver
    cmd: /app/vendor/acquia/blt/bin/blt
  npm:
    service: appserver
    cmd: npm
  xdebug-on:
    service: appserver
    description: Enable xdebug for Apache.
    cmd: docker-php-ext-enable xdebug && service apache2 reload
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for Apache.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && service apache2 reload
    user: root
  behat-build:
    description: build pre-requisites for behat testing.
    cmd:
      - appserver: cd /app/behat_rework && composer install
      - appserver: cd /app/behat_rework/bin && npm install
      - appserver: cd /app/behat_rework/ && ./behat-build.sh --rebuild=TRUE
  behat-run:
    description: runs behat tests
    service: appserver
    cmd: cd /app/behat_rework && ./bin/behat -vvv -c behat-lando.yml --format pretty
  logs-drupal:
    service: appserver
    description: Displays and tails Drupal logs using syslog module (because drush wd-show no longer supports tail)
    cmd:
      - /app/.lando/scripts/logs-drupal.sh
    user: root
  ssh-fix:
    service: appserver
    description: Fix ssh auth sock permission for MacOS users. Lando rebuild fixes the problem as well.
    cmd: "/bin/chgrp www-data /run/host-services/ssh-auth.sock && /bin/chmod g+w /run/host-services/ssh-auth.sock"
    user: root
  npm-fix:
    service: appserver
    description: Re-install the old / supported npm and node.
    cmd: "bash /app/.lando/scripts/install-npm.sh"
    user: root
  create-databases:
    service: appserver
    description: Create database for all the supported sites.
    cmd: "bash /app/.lando/scripts/provision/database.sh"
